# Site
repository: vishnu-indusekharan/resume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Vishnu Indusekharan
title: Network Development Engineer II
email: vishnu.indusekharan@gmail.com
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: jekyllrb
linkedin_username: vishnu-indusekharan
github_username: vishnu-indusekharan
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: vishnu.indusekharan
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ



# Additional icon links
#additional_links:
#- title: Download Resume
#  icon: fa-light fa-file-pdf
#  url: images/vishnu_indusekharan_resume.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/dp.jpg
about_content: | # this will include new lines to allow paragraphs
  Senior Network Engineer with 10+ years of experience architecting and scaling large-scale infrastructure solutions for global cloud environments. 
  Demonstrated expertise in migrating vendor based networks to whitebox platforms, with deep knowledge in routing, switching, multicast, and network automation. 
  Proven track record of leading complex migration programs handling 100+ Tbps of traffic while driving significant operational efficiencies through automation and infrastructure as code solutions. 
  Strong technical leadership in developing innovative tools and frameworks that enable data-driven m infrastructure decisions and support exponential growth.

  Works on:
  * Core Routing protocols: BGP, ISIS, OSPF, LDP, MPLS, RSVP, Controller based routing
  * Traffic engineering: RSVP-TE, SR, In house solutions in Amazon and Microsoft
  * Network Automation and Infrastructure as code.

  [Download my resume](images/Vishnu-Indusekharan-2025.pdf)
  
content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Amazon Web Service
        sub_title: Network Development Engineer II
        caption: June 2022 - Present
        description: |
         * Technologies : BGP, OSPF, MPLS, SR, TE, RSVP
         * Platform : Cisco, Juniper, CRPD, Commodity Hardware, BIRD, FRRouting
         * Languages : Python, Jina, Netconf, Yang, Infrastructure as code.

      - layout: left
        title: Microsoft
        sub_title: Network Service Engineer II
        caption: April 2021 - May 2022
        description: |
         * Technologies : BGP, ISIS, MPLS, SR, TE, RSVP
         * Platform : Cisco, Juniper, Arista, Sonic
         * Languages : Python, Kusto
         * Help customers to Plan, Design Implement and migrate new technologies on project-by-project basis.
         * Analyzing & rectifying the Design defects and implementing them with the help of stakeholders.

      - layout: left
        title: Cisco Systems
        sub_title: Consulting Engineer
        caption: Jan 2018 - May 2021
        description: |
          Handles Customer's issues related to below technologies on IOS, IOS-XE and IOS-XR
          * Routing : EIGRP, BGP, OSPF, ISIS, NAT, HSRP, PBR, Multicast, LISP
          * SP : MPLS, L2VPN, L3VPN, Traffic Engineering, RSVP, SR
          * WAN : ISG, BNG, L2TP/VPDN, CEM
          * ACCESS : PPP, DSL, ISDN, T1/E1, 3G/4G
          * Others : AAA, DHCP , RADIUS, TACACS+
          * Platform : ASR1k, ISR4K, ASR9K, ISRG2s

      - layout: left
        title: USEReady
        sub_title: Network Engineer
        caption: October 2016 - October 2017
        description: |
          * Working with individual businesses on analyzing the requirements for secure extranet connections 
          * Creating a design based on those requirements.
          * Performing installation and configuration migration and up-gradation of network devices.
          * Working on End of Life hardware upgrades on head end and remote end devices.
          * Implementing configurations and implementation instructions into Clientâ€™s change management

      - layout: left
        title: Cisco Systems
        sub_title: Tier 2 Network Engineer
        caption: October 2014 - October 2016
        description: |
          * Support for network related issues in Cisco sites and Cisco partner sites.
          * Identify, Troubleshoot and resolve LAN/WAN and Wireless network issues in window time.
          * Implement new network as per the client requirement.
          * Configuring the new Labs and extending the functionalities of existing Labs for CISCO Systems.
          
  - title: Certification
    layout: text
    content: |
          * CCIE SP #62851
          * CCNP R&S
          * CCNA R&S and Security
          * Specialist (IOS-XR, SP, Enterprise) 
          * JNCIA
          * Python

  - title: When I'm Not Working
    layout: text
    content: | # this will include new lines to allow paragraphs
      You will find me with my camera, I'm interested in photography and I enjoy landscape and macro photography along with Hiking. I like to showcase my work on instagram if
      you would like to take a look - [vishnu.indusekharan](https://www.instagram.com/vishnu.indusekharan/).


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
